In [ ]:
"""
本案例学习pytorch相关操作
张量的基本属性  dtype  grad 
1.张量创建
    基本创建
    torch.tensor（） torch.Tensor()  根据数据创建张量  根据形状创建张量
    torch.IntTensor() 根据形状创建张量时指定类型
    线性张量和随机张量
    torch.arange() torch.linspace() 创建线性张量
    torch.randn()  torch.rand()
    torch.initial_seed()  torch.manual_seed() 查看和设置随机种子
    创建0，1张量和指定值张量
    torch.zeros() torch.ones()
    torch.zeros_like() torch.ones_like()
    torch.full() torch.full_like()
    张量元素类型转换
    .type()  .float() .to()
    张量的类型转换
    tensor.numpy() tensor.numpy().copy()
    torch.from_numpy(ndarray) torch.from_numpy(ndarray.copy()) torch.Tensor()
    torch.item() torch.torch()
2.张量的运算
    基本运算
    数学计算
3.张量的索引操作

    """

In [1]:
# 致昨天，期待再见
import torch
import sys
import platform
from loguru import logger
def version_info():
    logger.info("本项目是pytorch基础")
    logger.info(f"系统版本:{platform.platform()}")
    logger.info(f"python版本:{sys.version,sys.version_info,platform.python_version()}")
    logger.info(f"pytorch版本:{torch.__version__}")# 查看version版本      python3.8-3.11 支持2.0.0
version_info()

2025-06-28 02:04:47.073 | INFO     | __main__:version_info:7 - 本项目是pytorch基础
2025-06-28 02:04:47.075 | INFO     | __main__:version_info:8 - 系统版本:Windows-10-10.0.26100-SP0
2025-06-28 02:04:47.076 | INFO     | __main__:version_info:9 - python版本:('3.10.0 | packaged by conda-forge | (default, Nov 10 2021, 13:20:59) [MSC v.1916 64 bit (AMD64)]', sys.version_info(major=3, minor=10, micro=0, releaselevel='final', serial=0), '3.10.0')
2025-06-28 02:04:47.076 | INFO     | __main__:version_info:10 - pytorch版本:2.4.0+cu124


In [2]:
# 1. 深度学习基础
      # 张量创建   # 张量的转化 # 张量的运算  # 张量的索引 # 张量的形状操作
# 2. Pytorch的基本使用
# 3. 神经网络基础
# 4. 卷积神经网络
# 5. 循环神经网络
# 6. transformer

In [3]:
# 张量 Tensor ，机器学习的基本构建模块，能保存梯度
# 在图像处理领域，一般用三维的张量表示三通道，高，宽表示图像
# 

In [24]:
# 张量的维度（ndim）和方括号层数对应，size()的方括号内就有几个数。张量的维度可以从0到无限多。
scalar=torch.tensor(7) # 源数据没有方括号，0维，
print(f"0维度的张量{scalar}",scalar,scalar.ndim,scalar.size())
vector=torch.tensor([1,2,3]) # 源数据只有一个方括号，1维，
print(f"1维度的张量{vector}",vector.ndim,vector.size())
matrix=torch.tensor([[1,2,3],[4,5,6]])  # 源数据二个方括号，2维
print(f"2维度的张量{matrix}",matrix.ndim,vector.size())
tensor=torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(f"多维度的张量{tensor}",tensor.ndim,tensor.size()) # 两通道，两行三列

0维度的张量7 tensor(7) 0 torch.Size([])
1维度的张量tensor([1, 2, 3]) 1 torch.Size([3])
2维度的张量tensor([[1, 2, 3],
        [4, 5, 6]]) 2 torch.Size([3])
多维度的张量tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]) 3 torch.Size([2, 2, 3])


In [7]:
# tensor()和Tensor()的区别  tensor()方法只能通过已有数据，如标量，数组，列表创建张量，Tensor()即可以通过数组和列表创建张量，也可以通过形状创建张量，注意Tensor(3)没有方括号被视为用形状创建。
import numpy as np
a=torch.tensor(2) # 根据数据创建
b=torch.Tensor(3) # 根据数据或形状，没有方括号的情况下都是指定形状
print(a,b)

# 由numpy创建数组，再通过数组创建tensor
np1=np.random.randn(2,3)
ts1=torch.tensor(np1)   # 数组创建
ts2=torch.tensor([[1,2,3],[2,3,4]])  # 列表创建
print(ts1)

ts23=torch.Tensor(2,3)
print(ts23,ts23.dtype)  # 默认是float

# 指定类型
tsint=torch.IntTensor(2,3)  # 等于 torch.Tensor(2,3,dtype=Int)
print(tsint,tsint.dtype)
tsDouble=torch.DoubleTensor(2,3)
print(tsDouble,tsDouble.dtype)

tensor(2) tensor([0., 0., 0.])
tensor([[ 0.2503, -0.3940,  1.1754],
        [-0.0426, -0.5220,  0.5532]], dtype=torch.float64)
tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 7.2447e-43]]) torch.float32
tensor([[        0,         0,         0],
        [        0,         0, 539767391]], dtype=torch.int32) torch.int32
tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64) torch.float64


In [3]:
# 创建线性和随机张量
# 线性张量
ts_246=torch.arange(0,10,2)#[start,end,step]左闭右开,step步长
print(ts_246)
ts_lin=torch.linspace(0,11,10)# [start,end,nums]左闭右闭，在区间内均匀地取多少个数
print(ts_lin)

# 设置和查看随机种子，torch.randn()生成固定张量 ，rand() ,randint()
# 查看随机种子
print(torch.random.initial_seed())
# 设置随机种子
print(torch.random.manual_seed(100))
# 创建满足正态分布的随即张量
print(torch.randn(2, 3))
# torch.Tensor(2,3)
print(torch.random.initial_seed())
# random.seed(42)
# np.random.seed(42)
# torch.cuda.manual_seed(42)
# 在 DataLoader 中设置参数 worker_init_fn 来设置每个 worker 的种子；
# 开启 PyTorch 的确定性算法（注意这可能会影响性能）：
# torch.use_deterministic_algorithms(True)

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  1.2222,  2.4444,  3.6667,  4.8889,  6.1111,  7.3333,  8.5556,
         9.7778, 11.0000])
284525191834800
tensor([[ 0.3607, -0.2859, -0.3938],
        [ 0.2429, -1.3833, -2.3134]])
100


In [143]:
# 创建01张量   zeros,ones,zeros_like,ones_like
ts_0=torch.zeros(2,3)
print(ts_0)
ts_1=torch.ones(2,3)
print(ts_1)
ts_rand=torch.rand(3,3)
print(ts_rand)
ts_randn=torch.randn(3,3)
print(ts_randn)
ts_zeros_like=torch.zeros_like(ts_rand)
print(ts_zeros_like)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.6868, 0.4920, 0.0748],
        [0.9605, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])
tensor([[-0.3420,  0.8223,  0.2766],
        [-0.9687, -0.7782,  0.5023],
        [ 0.5022,  0.8530, -0.4760]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [144]:
# full,full_like
# 创建指定值的张量
ts_10=torch.full([2,3],10) # 左形状，有指定值
print(ts_10)
ts_rand=torch.rand(3,3)
ts_10_like=torch.full_like(ts_rand,10)
print(ts_10_like)

tensor([[10, 10, 10],
        [10, 10, 10]])
tensor([[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]])


In [146]:
# 张量元素类型转换,short in16 int int32 long int64 float float32 double float64
#  type(),to(),float()
ts_int=torch.tensor([1,2,3],dtype=torch.int)
print(ts_int)
ts_float=ts_int.float()
print(ts_float)
ts_float2=ts_int.to(torch.double)
print(ts_float2)
ts_float3=ts_int.type(torch.DoubleTensor)
print(ts_float3)

tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float64)


In [17]:
# 张量与数组的转换
data_tensor=torch.tensor([2,3,4])
print(type(data_tensor))

# 共享内存的转换
data_numpy=data_tensor.numpy()
print(type(data_numpy))
print(data_tensor,data_numpy)
data_numpy[0]=100  
print(data_tensor,data_numpy)

# 用深拷贝不共享内存
data_numpy=data_tensor.numpy().copy()   # 这里的copy是深拷贝
print(type(data_numpy))
data_numpy[0]=200
print(data_tensor,data_numpy)

<class 'torch.Tensor'>
<class 'numpy.ndarray'>
tensor([2, 3, 4]) [2 3 4]
tensor([100,   3,   4]) [100   3   4]
<class 'numpy.ndarray'>
tensor([100,   3,   4]) [200   3   4]


In [160]:
data_np=np.array([2,3,4])
data_ts=torch.from_numpy(data_np)
data_ts[0]=100
print(data_np,data_ts)

torch.tensor(data_np) # 本身不共享内存
data_ts=torch.from_numpy(data_np.copy())

[100   3   4] tensor([100,   3,   4], dtype=torch.int32)


tensor([100,   3,   4], dtype=torch.int32)

In [6]:
# 用item()这个函数将只有一个元素的张量提取出来
data=torch.Tensor([30])
print(data.item())

data=torch.tensor(30)
print(data.item())
print(type(data.item()))

30.0
30
<class 'int'>


### 张量基本运算符号

In [15]:
data=torch.randint(0,10,[2,3]) # 左闭右开
print(data)
new=data.add(10)
print(new)
print(data)
# sub() mul() div() neg()

tensor([[3, 7, 0],
        [6, 7, 9]])
tensor([[13, 17, 10],
        [16, 17, 19]])
tensor([[3, 7, 0],
        [6, 7, 9]])


In [205]:
# 对应元素相乘
data1=torch.tensor([[1,2],[3,4]])
data2=torch.tensor([[5,6],[7,8]])
data3=data1.mul(data2)
data4=data1*data2
print(data3,data4)

# 矩阵乘法
# （n,m）(m,p)=(n,p) 相乘相加  
data5=data1.matmul(data2)
data6=data1@data2
print(data5,data6)

tensor([[ 5, 12],
        [21, 32]]) tensor([[ 5, 12],
        [21, 32]])
tensor([[19, 22],
        [43, 50]]) tensor([[19, 22],
        [43, 50]])


###  张量数学计算

In [214]:
data=torch.randint(0,10,[2,3],dtype=torch.float64)
print(data)
print(data.mean())
print(data.mean(dim=0))  # dim==0是最外层括号
print(data.mean(dim=1))

print(data.sum())
print(data.sum(dim=0))
print(data.sum(dim=1))

print(torch.pow(data,2))    # 幂函数

print(torch.sqrt(data))     # 平方根幂函数  等于pow(data,1/2)

print(torch.log(data))      # 对数函数

print(torch.exp(data))      # 指数函数

tensor([[3., 5., 2.],
        [5., 8., 8.]], dtype=torch.float64)
tensor(5.1667, dtype=torch.float64)
tensor([4.0000, 6.5000, 5.0000], dtype=torch.float64)
tensor([3.3333, 7.0000], dtype=torch.float64)
tensor(31., dtype=torch.float64)
tensor([ 8., 13., 10.], dtype=torch.float64)
tensor([10., 21.], dtype=torch.float64)
tensor([[ 9., 25.,  4.],
        [25., 64., 64.]], dtype=torch.float64)
tensor([[1.7321, 2.2361, 1.4142],
        [2.2361, 2.8284, 2.8284]], dtype=torch.float64)
tensor([[1.0986, 1.6094, 0.6931],
        [1.6094, 2.0794, 2.0794]], dtype=torch.float64)
tensor([[  20.0855,  148.4132,    7.3891],
        [ 148.4132, 2980.9580, 2980.9580]], dtype=torch.float64)


### 张量的索引操作

In [ ]:
# 注意区分列表的索引操作 和  tensor的索引操作
# x=[[1,2,3],[4,5,6]]
# print(x[1][0])
# print(x[0])取第一行
# 不能用 [:,0] 取第一列这是ndarray和tensor的用法；也不能用[:][0]，这个实际上也是取第一行
# 只能用list(zip(*data))[0]或者[row[0] for row in data]

In [27]:
# 注意与列表的索引操作作区分
# x=[[1,2,3],[4,5,6]]
# print(x[1][0])
import torch  # 列表索引 布尔索引 范围索引
torch.manual_seed(100)
data=torch.randint(0,10,[4,5])    # 两句话，布尔索引看作正常的索引参与广播机制。:是例外的广播机制，可能会导致升维度。
print(data)
# print(data[0])   # 取第一行
# print(data[0][0]) # 取第一行的第一列
# print(data[:,0])    # 取第一列
# print(data[0,0])      # 取第一行的第一列
# print(data[[0,1],[1,2]]) # 无需广播，自动组合成 [(0,1),(1,2)]
# print(data[[0],[1]],[1,2])  # 需要广播 （2，1）和（2） 广播成（2，2）
# 广播规则
# 从右往左对齐；
# 左侧不足补1；
# 每个维度判断兼容性（相等 or 1）；
print(data[[0,1],[[1],[2]]])
#(2,),(2,1)
# (2,),(2,2)   [0,1],[[1,1],[2,2]]
# (2,2),(2,2)  [[0,1],[0,1]],[[1,1],[2,2]]
# [[(0,1),(1,1)],[(0,2),(1,2)]]
'''第一个维度的索引是 [0,1]
第二个维度的索引是 [[1],[2]]
这种索引方式会进行广播匹配，实际上相当于访问以下位置的元素：
(0,1)
(0,2)
(1,1)
(1,2)'''

# print(data[:3,:2])
print(torch.tensor([2,3]).size())
print(data[[2,2],[[1,2],[3,4]]])   # (4,2,2)
print(data[[False,True,True,False],[[1,2],[3,4]]])

#范围索引不广播
print(data[:2,[[1],[2]]])  # :的包容          # （4，5）+（2，1）==（4，2，1）   (2,5)+(2,1)==(2,2,1)
print(data[data[:,2]>5,[[1],[2]]])  
print(data[[[1],[2]],:])   # 他的广播机制可能会导致升维度 （2，1）+（4，5）==（2，1，5）

tensor([[0, 2, 5, 9, 5],
        [1, 2, 8, 8, 0],
        [4, 3, 8, 8, 4],
        [4, 1, 0, 4, 3]])
tensor([[2, 2],
        [5, 8]])
torch.Size([2])
tensor([[3, 8],
        [8, 4]])
tensor([[2, 8],
        [8, 4]])
tensor([[[2],
         [5]],

        [[2],
         [8]]])
tensor([[2, 3],
        [8, 8]])
tensor([[[1, 2, 8, 8, 0]],

        [[4, 3, 8, 8, 4]]])


In [28]:
# 布尔索引 保存【】，参与广播机制，没有方括号代表降维，该位置没有方括号。
print(data[data[:,2]>5])  # 
# （4，5）=（2，5）

print(data[:,data[0]>5])   # （4，5）+（2）=（4，2）
print(data[:,data[1]>5])   # （4，5）+（2）=（4，2）


tensor([[1, 2, 8, 8, 0],
        [4, 3, 8, 8, 4]])
tensor([[9],
        [8],
        [8],
        [4]])


In [231]:
# 布尔索引
data=torch.randint(0,10,[3,4,5])
print(data)
print(data[0,:,:]) # 

tensor([[[0, 1, 1, 4, 0],
         [2, 4, 1, 5, 3],
         [2, 5, 9, 6, 2],
         [6, 5, 1, 2, 5]],

        [[4, 9, 8, 0, 0],
         [2, 5, 2, 1, 1],
         [1, 3, 3, 5, 7],
         [8, 9, 5, 3, 0]],

        [[3, 5, 7, 7, 2],
         [5, 8, 5, 2, 3],
         [1, 9, 3, 3, 2],
         [2, 4, 8, 0, 0]]])
tensor([[0, 1, 1, 4, 0],
        [2, 4, 1, 5, 3],
        [2, 5, 9, 6, 2],
        [6, 5, 1, 2, 5]])


### 张量形状操作

In [55]:
# torch.reshape()   # 元素重排列
# tensor.view(shape)  # 操作的tensor必须再连续内存空间内
# tensor.contiguous()  # 将tensor放在连续内存空间内
# torch.stack(tensors,dim=1) # 将相同形状的tensor堆叠在一起，维度升高
# torch.squeeze(input)    # 降低维度，减少括号
# torch.unsqueeze(input)  # 生维度，增加括号
# torch.transpose(input,dim1,dim2)  # 维度变换，元素相对位置不变，维度优先级的问题
# torch.permute(input,dims)  # 形状变换，可指定多个维度

# transpose和permute仅改变形状和步幅，不复制数据，步幅度指的是从逻辑索引到物理内存位置的映射规则。
'''视图（View）特性：
transpose和permute返回的是原张量的视图，仅修改元数据（形状、步幅），不复制数据。
步幅（Stride）调整：
例如，原张量形状为(2, 3)，步幅为(3, 1)，转置后形状为(3, 2)，步幅变为(1, 3)。元素通过新步幅访问，但内存位置未变。
4. 注意事项
连续性（Contiguity）：
transpose和permute可能导致张量不连续（如转置后的矩阵）。若需要连续张量（如某些运算要求），需显式调用.contiguous()，此时会触发数据复制，物理存储改变。'''

import torch
x=torch.arange(1.,8.)
print(x)
print(x.size())
print(x.shape)
# reshape扩为度
x_reshaped=x.reshape(1,7)
print(x_reshaped)

data=torch.tensor([[10,20,30],[40,50,60]])
print(data.reshape(1,6))
print(data.reshape(3,2))

print(data.view(3,2))
print(data.is_contiguous())
data=data.view(3,2)
print(data.is_contiguous())

tensor([1., 2., 3., 4., 5., 6., 7.])
torch.Size([7])
torch.Size([7])
tensor([[1., 2., 3., 4., 5., 6., 7.]])
tensor([[10, 20, 30, 40, 50, 60]])
tensor([[10, 20],
        [30, 40],
        [50, 60]])
tensor([[10, 20],
        [30, 40],
        [50, 60]])
True
True


In [61]:
x=torch.arange(1,8)
x_stacked=torch.stack([x,x,x],dim=0)
print(x_stacked)

tensor([[1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7]])


In [ ]:
#squeeze unsqueeze


In [ ]:
# transpose permute  交换维度，导致不连续，数据相对位置不变


tensor.permute()
data.permute

### 拼接操作

In [ ]:
torch.cat()

# 自动微分模块

In [ ]:
# 机器学习的监督学习
# 1.准备数据：特征和目标 ，2.设计模型，损失函数和优化算法。
# 2.获得模型

# 机器学习的线性回归
# data：一组 x,y ,向量x=[1,x1,x2,x3]和标量y  ps:线性回归只有一个输出，类似于神经网络中的一个神经元
# model h(x)=θT⋅x    loss= MSE()= 1/m⋅(y^-y)²  优化方法：梯度下降

# 线性回归到神经网络
# 线性回归模型公式上是多元一次方程，几何上是拟合直线，平面，超级平面。
# 如果为多元一次方程组引入激活函数，也就是引入非线性，那么这样的模型可以拟合曲线，曲面和超曲面。而这，就是一个神经元。
# 如果我们将神经元模型叠加，就可以实现曲面叠加，形成网络层，可以拟合更复杂的情况和关系。

In [ ]:
# 基本概念：
# 梯度下降是一种最优化算法，通过沿着函数的梯度负方向迭代来寻找函数的局部最小值。

# 梯度表示函数在某一点的最陡峭方向
# 梯度的反方向指向函数值下降最快的方向
# 通过沿着梯度的反方向迭代移动，最终到达局部最小值


# 梯度下降算法是一种优化目标函数的迭代方法，通过不断调整参数值，使得目标函数值逐步减小。最终找到最小值或接近最小值。

# 1.目标函数：
# 梯度下降的目标是最小化一个函数 J(θ)，其中 θ 是模型的参数（如权重）。
# 2.梯度：
# 梯度是目标函数对参数的偏导数向量，表示函数在参数空间中的变化方向。梯度 ∇J(θ) 指向函数值增加最快的方向。
# 3.更新规则：梯度下降通过以下公式更新参数：
# θ = θ - α * ∇J(θ)
# 其中，α 是学习率，控制每次更新的步长。
# 4.迭代过程：
# 从初始参数 θ0开始，反复计算梯度并更新参数，直到满足停止条件（如梯度接近零或达到最大迭代次数）。

# 关键点
# 学习率：α 的选择至关重要：过大可能导致震荡或发散。过小则收敛速度慢。
# 
# 局部最优与全局最优：
# 梯度下降可能陷入局部最优，尤其是在非凸函数中。初始参数和优化策略会影响结果。
# 
# 批量梯度下降（BGD）：
# 每次迭代使用整个数据集计算梯度，计算开销大但稳定。
# 
# 随机梯度下降（SGD）：
# 每次迭代随机选择一个样本计算梯度，计算效率高但波动较大。
# 
# 小批量梯度下降（Mini-batch GD）：
# 折中方案，每次使用一个小批量样本计算梯度，兼顾效率和稳定性。

In [ ]:
# 在线性回归中，目标函数（损失函数）是最小化均方误差（MSE）：
# 
# J(θ)=1/2m*(m∑i=1)(hθ(x(i))−y(i))²
# 
# hθ(x)=θT*x 是预测函数。
# 
# m m 是样本数量。
# 
# 系数 1/2是为了简化梯度计算而引入的。

# θ j=θ j−α⋅ (1/m)⋅   (i=1∑m)(h θ(x (i))−y (i))⋅x j(i)


# α 是学习率。
# 
# hθ(x(i))=θTx(i)是预测值。
# 
# y(i)是真实值。
# 
# x j(i)  是第 i个样本的第 j 个特征。                             




In [ ]:
# θ 为参数，α 为学习率，∇J(θ) 为损失函数对参数的梯度
# θ = θ - α * ∇J(θ)

# 对于参数来说

In [25]:
import torch

x = torch.tensor([1.0], requires_grad=True)
y = x * 2
z = y * 3

# 计算图会随着运算的执行即时构建
z.backward()
print(x.grad)  # 输出 tensor([6.])

tensor([6.])


In [26]:
# 代码执行到哪里，计算图就构建到哪里
x = torch.tensor([2.0], requires_grad=True)
if x > 1:
    y = x * 2
else:
    y = x + 2
# 计算图会根据实际执行的分支构建

In [5]:
x=torch.tensor(5.)
y=torch.tensor(0.)
print(x,x.dtype,y)
w=torch.tensor(1.,requires_grad=True)
b=torch.tensor(3.,requires_grad=True)

z=x*w+b
loss=torch.nn.MSELoss()

loss=loss(z,y)
print(loss)

loss.backward()

print(w.grad)
print(b.grad)

tensor(5.) torch.float32 tensor(0.)
tensor(64., grad_fn=<MseLossBackward0>)
tensor(80.)
tensor(16.)


In [79]:
import torch
device=torch.device('cuda')
x=torch.ones(2,5)
y=torch.zeros(2,3)
x.to(device)
y.to(device)
print(x,y)
w=torch.randn(5,3,requires_grad=True)
b=torch.randn(3,requires_grad=True)
w.to(device)
b.to(device)
z=x@w+b

loss=torch.nn.MSELoss()

loss=loss(z,y)
loss.backward()

print(w.grad)
print(b.grad)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1.2742, 0.6795, 0.9647],
        [1.2742, 0.6795, 0.9647],
        [1.2742, 0.6795, 0.9647],
        [1.2742, 0.6795, 0.9647],
        [1.2742, 0.6795, 0.9647]])
tensor([1.2742, 0.6795, 0.9647])
